import { prisma } from "@/lib/prisma";
import { ABSENCE_TRACKING_FROM } from "@/lib/attendance-engine";
import { getDictionary } from "@/lib/i18n";
import { dayStr } from "@/lib/serialize";
import { addDays, localDay } from "@/lib/today";
import {
  LeaveForAbsence,
  PayableEmployee,
  absenceDaysCharged,
  dayRate,
  earlyLeaveDeduction,
  lateDeduction,
  payPeriodOf,
} from "@/lib/pay-rules";

export type SystemDeductionType = "late" | "absence" | "early_leave";

export interface SystemDeduction {
  systemKey: string;
  employeeId: string;
  date: string;
  type: SystemDeductionType;
  amount: number;
  reason: string;
}

export interface AttendanceDay {
  employeeId: string;
  date: string;
  status: string;
  lateMinutes: number;
  earlyLeaveMinutes: number;
  scheduledStart: Date;
}

export const systemKey = (employeeId: string, date: string, type: SystemDeductionType) => `${employeeId}|${date}|${type}`;

/** The deductions the bylaws put on one finished day of attendance. Zero amounts (no salary entered yet) are
 * left out rather than posted as empty rows. Reasons are written in Arabic, the company's working language. */
export function systemDeductionsFor(day: AttendanceDay, employee: PayableEmployee, leave: LeaveForAbsence | null): SystemDeduction[] {
  const out: SystemDeduction[] = [];
  const add = (type: SystemDeductionType, amount: number, reason: string) => {
    if (amount > 0) out.push({ systemKey: systemKey(day.employeeId, day.date, type), employeeId: day.employeeId, date: day.date, type, amount, reason });
  };

  const days = absenceDaysCharged(day.status, leave, day.scheduledStart);
  if (days > 0) {
    add(
      "absence",
      Math.round(days * dayRate(employee)),
      days === 1 ? "غياب بإذن معتمد قبلها بـ48 ساعة — اليوم بيوم" : "غياب بدون إذن مسبق — اليوم بيومين",
    );
    return out; // a day off has no lateness or early leave on top
  }
  if (day.lateMinutes > 0) add("late", lateDeduction(employee, day.lateMinutes), `تأخير ${day.lateMinutes} دقيقة — الساعة بساعتين ونصف`);
  if (day.earlyLeaveMinutes > 0) add("early_leave", earlyLeaveDeduction(employee, day.earlyLeaveMinutes), `انصراف مبكر ${day.earlyLeaveMinutes} دقيقة`);
  return out;
}

export interface ExistingSystemDeduction {
  id: string;
  systemKey: string;
  amount: number;
  reason: string;
  edited: boolean;
  voided: boolean;
}

/**
 * What to change so the posted deductions match the days: create what's missing, update what changed, and
 * remove what no longer applies (the day was corrected, a leave was approved). A deduction someone edited or
 * removed by hand is theirs — it is never touched again.
 */
export function planSystemDeductions(desired: SystemDeduction[], existing: ExistingSystemDeduction[]) {
  const byKey = new Map(existing.map((e) => [e.systemKey, e]));
  const wanted = new Set(desired.map((d) => d.systemKey));
  const create: SystemDeduction[] = [];
  const update: { id: string; amount: number; reason: string }[] = [];
  for (const d of desired) {
    const e = byKey.get(d.systemKey);
    if (!e) create.push(d);
    else if (!e.edited && !e.voided && (e.amount !== d.amount || e.reason !== d.reason)) update.push({ id: e.id, amount: d.amount, reason: d.reason });
  }
  const remove = existing.filter((e) => !wanted.has(e.systemKey) && !e.edited && !e.voided).map((e) => e.id);
  return { create, update, remove };
}

/** How far back the job keeps deductions in step: a little over two pay months. */
const LOOKBACK_DAYS = 70;

/**
 * Posts (and keeps in step) the deductions for every finished day: absences, lateness and early leave, from
 * the day's attendance. Only days before today, so a day is only charged once it's over, and never inside a
 * pay month that has already been approved or closed.
 */
export async function postAttendanceDeductions(now: Date = new Date()): Promise<{ created: number; updated: number; removed: number }> {
  const today = localDay(now);
  const lastDay = addDays(today, -1);
  const lookback = addDays(today, -LOOKBACK_DAYS);
  const firstDay = lookback > ABSENCE_TRACKING_FROM ? lookback : ABSENCE_TRACKING_FROM;
  if (lastDay < firstDay) return { created: 0, updated: 0, removed: 0 };

  const range = { gte: new Date(`${firstDay}T00:00:00.000Z`), lte: new Date(`${lastDay}T00:00:00.000Z`) };
  const [days, employees, leaves, periods, existing] = await Promise.all([
    prisma.dailyAttendance.findMany({ where: { date: range } }),
    prisma.employee.findMany({ where: { deletedAt: null } }),
    prisma.leave.findMany({ where: { status: "approved", to: { gte: range.gte }, from: { lte: range.lte } } }),
    prisma.payrollPeriod.findMany({ where: { status: { in: ["approved", "closed"] } } }),
    prisma.deduction.findMany({ where: { autoGenerated: true, systemKey: { not: null }, date: range } }),
  ]);

  const locked = new Set(periods.map((p) => `${p.year}-${p.month}`));
  const isLocked = (day: string) => {
    const p = payPeriodOf(day);
    return locked.has(`${p.year}-${p.month}`);
  };
  const employeeById = new Map(employees.map((e) => [e.id, e]));

  const desired: SystemDeduction[] = [];
  for (const d of days) {
    const date = dayStr(d.date);
    const employee = employeeById.get(d.employeeId);
    if (!employee || isLocked(date)) continue;
    const leave =
      leaves.find((l) => l.employeeId === d.employeeId && dayStr(l.from) <= date && dayStr(l.to) >= date) ?? null;
    desired.push(
      ...systemDeductionsFor(
        { employeeId: d.employeeId, date, status: d.status, lateMinutes: d.lateMinutes, earlyLeaveMinutes: d.earlyLeaveMinutes, scheduledStart: d.scheduledStart },
        employee,
        leave,
      ),
    );
  }

  const plan = planSystemDeductions(
    desired,
    existing
      .filter((e) => !isLocked(dayStr(e.date)))
      .map((e) => ({ id: e.id, systemKey: e.systemKey!, amount: e.amount, reason: e.reason, edited: Boolean(e.editedAt), voided: Boolean(e.voidedAt) })),
  );
  const changes = plan.create.length + plan.update.length + plan.remove.length;
  if (changes === 0) return { created: 0, updated: 0, removed: 0 };

  // Written in the company's language and signed by the system, not by whoever happened to be logged in.
  const t = getDictionary("ar");
  await prisma.$transaction(async (tx) => {
    for (const c of plan.create) {
      await tx.deduction.create({
        data: {
          employeeId: c.employeeId,
          type: c.type,
          amount: c.amount,
          date: new Date(`${c.date}T00:00:00.000Z`),
          reason: c.reason,
          autoGenerated: true,
          systemKey: c.systemKey,
        },
      });
    }
    for (const u of plan.update) await tx.deduction.update({ where: { id: u.id }, data: { amount: u.amount, reason: u.reason } });
    if (plan.remove.length > 0) await tx.deduction.deleteMany({ where: { id: { in: plan.remove } } });
    await tx.auditLogEntry.create({
      data: {
        userName: t.auditActions.system,
        module: t.nav.deductions,
        action: t.auditActions.systemDeductions,
        oldValue: "-",
        newValue: `+${plan.create.length} / ~${plan.update.length} / -${plan.remove.length}`,
      },
    });
  });
  return { created: plan.create.length, updated: plan.update.length, removed: plan.remove.length };
}
