/**
 * Maps Prisma rows to the plain `src/lib/types.ts` shapes the UI and the pure
 * engines already expect — notably rendering DB `DateTime` columns back as the
 * ISO / `yyyy-MM-dd` strings the rest of the app works with.
 */
import type {
  Allowance as PAllowance,
  AttendanceLog as PAttendanceLog,
  AuditLogEntry as PAuditLogEntry,
  DailyAttendance as PDailyAttendance,
  Deduction as PDeduction,
  Department as PDepartment,
  Employee as PEmployee,
  Leave as PLeave,
  Overtime as POvertime,
  PayrollPeriod as PPayrollPeriod,
  PayrollRecord as PPayrollRecord,
  Shift as PShift,
} from "@prisma/client";
import type {
  Allowance,
  AttendanceLog,
  AuditLogEntry,
  DailyAttendance,
  Deduction,
  Department,
  Employee,
  Leave,
  Overtime,
  PayrollPeriod,
  PayrollRecord,
  Shift,
} from "@/lib/types";

export const dayStr = (d: Date): string => d.toISOString().slice(0, 10);
const iso = (d: Date): string => d.toISOString();
const isoOrNull = (d: Date | null): string | null => (d ? d.toISOString() : null);

export function toEmployee(e: PEmployee): Employee {
  return {
    id: e.id,
    name: e.name,
    departmentId: e.departmentId,
    jobTitle: e.jobTitle,
    hireDate: dayStr(e.hireDate),
    shiftId: e.shiftId,
    basicSalary: e.basicSalary,
    allowances: e.allowancesTotal,
    biometricDeviceUserId: e.biometricDeviceUserId,
    status: e.status,
    phone: e.phone ?? undefined,
    avatarColor: e.avatarColor ?? undefined,
  };
}

export function toDepartment(d: PDepartment): Department {
  return { id: d.id, name: d.name, managerName: d.managerName };
}

export function toShift(s: PShift): Shift {
  return {
    id: s.id,
    name: s.name,
    startTime: s.startTime,
    endTime: s.endTime,
    gracePeriodMinutes: s.gracePeriodMinutes,
    workDays: (s.workDays as number[]) ?? [],
    allowOvertime: s.allowOvertime,
  };
}

export function toAttendanceLog(l: PAttendanceLog): AttendanceLog {
  return {
    id: l.id,
    employeeId: l.employeeId,
    deviceId: l.deviceId ?? "",
    timestamp: iso(l.timestamp),
    punchType: l.punchType,
    source: l.source === "biometric" ? "simulated" : l.source,
  };
}

export function toDailyAttendance(a: PDailyAttendance): DailyAttendance {
  return {
    id: a.id,
    employeeId: a.employeeId,
    date: dayStr(a.date),
    shiftId: a.shiftId,
    scheduledStart: iso(a.scheduledStart),
    scheduledEnd: iso(a.scheduledEnd),
    actualIn: isoOrNull(a.actualIn),
    actualOut: isoOrNull(a.actualOut),
    lateMinutes: a.lateMinutes,
    deductibleLateMinutes: a.deductibleLateMinutes,
    earlyLeaveMinutes: a.earlyLeaveMinutes,
    workedMinutes: a.workedMinutes,
    overtimeMinutes: a.overtimeMinutes,
    status: a.status,
    correctionReason: a.correctionReason ?? undefined,
    correctedBy: a.correctedBy ?? undefined,
    correctedAt: isoOrNull(a.correctedAt) ?? undefined,
  };
}

export function toLeave(l: PLeave): Leave {
  return {
    id: l.id,
    employeeId: l.employeeId,
    type: l.type,
    from: dayStr(l.from),
    to: dayStr(l.to),
    reason: l.reason,
    status: l.status,
    approvedBy: l.approvedBy ?? undefined,
    createdAt: iso(l.createdAt),
  };
}

export function toOvertime(o: POvertime): Overtime {
  return {
    id: o.id,
    employeeId: o.employeeId,
    date: dayStr(o.date),
    hours: o.hours,
    hourlyRate: o.hourlyRate,
    amount: o.amount,
    status: o.status,
    approvedBy: o.approvedBy ?? undefined,
    notes: o.notes ?? undefined,
    createdAt: iso(o.createdAt),
  };
}

export function toDeduction(d: PDeduction): Deduction {
  return {
    id: d.id,
    employeeId: d.employeeId,
    type: d.type,
    amount: d.amount,
    date: dayStr(d.date),
    reason: d.reason,
    notes: d.notes ?? undefined,
    createdAt: iso(d.createdAt),
    autoGenerated: d.autoGenerated,
  };
}

export function toAllowance(a: PAllowance): Allowance {
  return {
    id: a.id,
    employeeId: a.employeeId,
    type: a.type,
    amount: a.amount,
    monthly: a.monthly,
    notes: a.notes ?? undefined,
  };
}

export function toPayrollPeriod(p: PPayrollPeriod): PayrollPeriod {
  return {
    id: p.id,
    label: p.label,
    year: p.year,
    month: p.month,
    status: p.status,
    calculatedAt: isoOrNull(p.calculatedAt) ?? undefined,
    approvedAt: isoOrNull(p.approvedAt) ?? undefined,
    closedAt: isoOrNull(p.closedAt) ?? undefined,
  };
}

export function toPayrollRecord(r: PPayrollRecord): PayrollRecord {
  return {
    id: r.id,
    periodId: r.periodId,
    employeeId: r.employeeId,
    basicSalary: r.basicSalary,
    allowances: r.allowances,
    overtimeAmount: r.overtimeAmount,
    incentives: r.incentives,
    bonuses: r.bonuses,
    grossSalary: r.grossSalary,
    lateDeduction: r.lateDeduction,
    absenceDeduction: r.absenceDeduction,
    earlyLeaveDeduction: r.earlyLeaveDeduction,
    penalties: r.penalties,
    advances: r.advances,
    otherDeductions: r.otherDeductions,
    totalDeductions: r.totalDeductions,
    netSalary: r.netSalary,
  };
}

export function toAuditLogEntry(a: PAuditLogEntry): AuditLogEntry {
  return {
    id: a.id,
    userName: a.userName,
    action: a.action,
    module: a.module,
    oldValue: a.oldValue,
    newValue: a.newValue,
    reason: a.reason ?? undefined,
    timestamp: iso(a.timestamp),
  };
}
