export type Role = "admin" | "hr" | "supervisor" | "employee";

export interface User {
  id: string;
  name: string;
  email: string;
  role: Role;
  employeeId?: string; // linked employee record, for supervisor/employee roles
  departmentId?: string; // for supervisor scoping
}

export type EmployeeStatus = "active" | "on_leave" | "suspended" | "terminated";

export interface Employee {
  id: string; // EMP-1001
  name: string;
  departmentId: string;
  jobTitle: string;
  hireDate: string; // ISO date
  shiftId: string;
  basicSalary: number;
  allowances: number; // fixed monthly allowances total (for quick display; itemized in Allowance[])
  biometricDeviceUserId: string;
  status: EmployeeStatus;
  phone?: string;
  avatarColor?: string;
}

export interface Department {
  id: string;
  name: string;
  managerName: string;
}

export interface Shift {
  id: string;
  name: string;
  startTime: string; // "08:00"
  endTime: string; // "16:00" (may cross midnight)
  gracePeriodMinutes: number;
  workDays: number[]; // 0=Sunday..6=Saturday
  allowOvertime: boolean;
}

export type PunchType = "in" | "out";
export type PunchSource = "simulated" | "manual_correction";

/** Immutable raw biometric record. Never edited or deleted. */
export interface AttendanceLog {
  id: string;
  employeeId: string;
  deviceId: string;
  timestamp: string; // ISO datetime
  punchType: PunchType;
  source: PunchSource;
}

export type AttendanceStatus =
  | "present"
  | "late"
  | "absent"
  | "leave"
  | "mission"
  | "excused_absence"
  | "early_leave"
  | "missing_punch";

export interface DailyAttendance {
  id: string;
  employeeId: string;
  date: string; // ISO date (yyyy-MM-dd)
  shiftId: string;
  scheduledStart: string; // ISO datetime
  scheduledEnd: string; // ISO datetime
  actualIn: string | null; // ISO datetime
  actualOut: string | null; // ISO datetime
  lateMinutes: number;
  deductibleLateMinutes: number;
  earlyLeaveMinutes: number;
  workedMinutes: number;
  overtimeMinutes: number;
  status: AttendanceStatus;
  correctionReason?: string;
  correctedBy?: string;
  correctedAt?: string;
}

export type LeaveType =
  | "annual"
  | "casual"
  | "sick"
  | "unpaid"
  | "mission"
  | "permission"
  | "excused_absence";

export type RequestStatus = "pending" | "approved" | "rejected";

export interface Leave {
  id: string;
  employeeId: string;
  type: LeaveType;
  from: string; // ISO date
  to: string; // ISO date
  reason: string;
  status: RequestStatus;
  approvedBy?: string;
  createdAt: string;
}

export interface Overtime {
  id: string;
  employeeId: string;
  date: string;
  hours: number;
  hourlyRate: number;
  amount: number;
  status: RequestStatus;
  approvedBy?: string;
  notes?: string;
  createdAt: string;
}

export type DeductionType =
  | "late"
  | "absence"
  | "early_leave"
  | "penalty"
  | "advance"
  | "admin_deduction"
  | "other";

export interface Deduction {
  id: string;
  employeeId: string;
  type: DeductionType;
  amount: number;
  date: string;
  reason: string;
  notes?: string;
  createdAt: string;
  autoGenerated?: boolean;
}

export type AllowanceType = "transport" | "meal" | "fixed" | "incentive" | "bonus";

export interface Allowance {
  id: string;
  employeeId: string;
  type: AllowanceType;
  amount: number;
  monthly: boolean;
  notes?: string;
}

export type PayrollPeriodStatus = "draft" | "calculated" | "approved" | "closed";

export interface PayrollPeriod {
  id: string;
  label: string; // "أغسطس 2026"
  year: number;
  month: number; // 1-12
  status: PayrollPeriodStatus;
  calculatedAt?: string;
  approvedAt?: string;
  closedAt?: string;
}

export interface PayrollRecord {
  id: string;
  periodId: string;
  employeeId: string;
  basicSalary: number;
  allowances: number;
  overtimeAmount: number;
  incentives: number;
  bonuses: number;
  grossSalary: number;
  lateDeduction: number;
  absenceDeduction: number;
  earlyLeaveDeduction: number;
  penalties: number;
  advances: number;
  otherDeductions: number;
  totalDeductions: number;
  netSalary: number;
}

export interface AuditLogEntry {
  id: string;
  userName: string;
  action: string; // e.g. "تعديل حضور"
  module: string; // e.g. "الحضور والانصراف"
  oldValue: string;
  newValue: string;
  reason?: string;
  timestamp: string;
}

export interface CompanySettings {
  companyName: string;
  logoUrl: string;
  address: string;
  phone: string;
}

export interface AttendanceSettings {
  defaultGracePeriodMinutes: number;
  lateDeductionPerMinute: number; // EGP per minute, demo rule
  earlyLeaveDeductionPerMinute: number;
  absenceDeductionDays: number; // how many days' salary deducted per absence
}

export interface PayrollSettings {
  overtimeHourlyMultiplier: number; // multiplier applied on basic hourly rate
  workingDaysPerMonth: number;
  workingHoursPerDay: number;
}
