"use client";

import { useMemo, useState, useTransition } from "react";
import { toast } from "sonner";
import { Trash2, MinusCircle } from "lucide-react";
import { Deduction, Employee } from "@/lib/types";
import { deleteDeduction } from "@/lib/actions/deductions";
import { formatEGP } from "@/lib/constants";
import { format } from "@/lib/i18n/format";
import { deductionTypeLabel } from "@/lib/i18n/labels";
import { useLocale, useT } from "@/components/providers/locale-provider";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import { EmptyState } from "@/components/shared/empty-state";
import { EditDeductionDialog } from "@/components/deductions/edit-deduction-dialog";
import { DeductionDetailsDialog, EntryContext } from "@/components/shared/entry-details-dialog";

export function DeductionsTable({
  deductions,
  employees,
  canManage,
  initialMonth = null,
  monthLabel,
  context = {},
}: {
  deductions: Deduction[];
  employees: Employee[];
  canManage: boolean;
  /** "YYYY-MM" to pre-filter by, e.g. from a dashboard KPI link (`?month=2026-08`). */
  initialMonth?: string | null;
  monthLabel?: string | null;
  /** per-row extras for the details popup: department, pay type and that day's attendance */
  context?: Record<string, EntryContext>;
}) {
  const t = useT();
  const locale = useLocale();
  const empMap = new Map(employees.map((e) => [e.id, e]));
  const [pending, startTransition] = useTransition();
  const [month, setMonth] = useState(initialMonth);
  const [details, setDetails] = useState<Deduction | null>(null);

  const rows = useMemo(
    () => (month ? deductions.filter((d) => d.date.startsWith(month)) : deductions),
    [deductions, month],
  );

  const filterLabel = monthLabel ?? month;

  if (deductions.length === 0) {
    return <EmptyState icon={MinusCircle} title={t.deductions.noDeductions} />;
  }

  return (
    <div className="flex flex-col gap-4">
      {month && (
        <div className="flex items-center justify-between rounded-lg border border-border bg-muted/40 px-4 py-2 text-sm">
          <span className="text-muted-foreground">{format(t.common.filteredBy, { label: filterLabel ?? "" })}</span>
          <button
            type="button"
            className="font-medium text-primary hover:underline"
            onClick={() => setMonth(null)}
          >
            {t.common.clearFilter}
          </button>
        </div>
      )}

      <p className="text-xs text-muted-foreground">{t.entryDetails.openRow}</p>

      {rows.length === 0 ? (
        <EmptyState icon={MinusCircle} title={t.deductions.noDeductions} />
      ) : (
    <div className="overflow-hidden rounded-xl border border-border">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>{t.deductions.colEmployee}</TableHead>
            <TableHead>{t.deductions.colType}</TableHead>
            <TableHead>{t.deductions.colAmount}</TableHead>
            <TableHead>{t.deductions.colDate}</TableHead>
            <TableHead>{t.deductions.colReason}</TableHead>
            {canManage && <TableHead className="text-end">{t.deductions.colActions}</TableHead>}
          </TableRow>
        </TableHeader>
        <TableBody>
          {rows.map((d) => {
            const employee = empMap.get(d.employeeId);
            return (
              <TableRow
                key={d.id}
                onClick={() => setDetails(d)}
                className="cursor-pointer"
                title={t.entryDetails.hint}
              >
                <TableCell>
                  <div className="font-medium">{employee?.name ?? "-"}</div>
                  {employee && <div dir="ltr" className="text-xs text-muted-foreground">{employee.employeeNumber}</div>}
                </TableCell>
                <TableCell>
                  <div className="flex flex-wrap items-center gap-1">
                    <Badge variant="destructive">{deductionTypeLabel(d.type, t)}</Badge>
                    {d.autoGenerated && (
                      <Badge variant="outline" title={d.editedBy ? format(t.deductions.editedBy, { name: d.editedBy }) : undefined}>
                        {d.editedBy ? t.deductions.systemEdited : t.deductions.fromSystem}
                      </Badge>
                    )}
                  </div>
                </TableCell>
                <TableCell className="tabular-nums font-medium text-destructive">
                  -{formatEGP(d.amount, locale)}
                  {d.editedBy && d.originalAmount != null && (
                    <div className="text-xs font-normal text-muted-foreground">{format(t.dayPay.original, { value: formatEGP(d.originalAmount, locale) })}</div>
                  )}
                </TableCell>
                <TableCell>{d.date}</TableCell>
                <TableCell className="max-w-[220px] truncate text-muted-foreground">{d.reason}</TableCell>
                {canManage && (
                  <TableCell className="text-end" onClick={(e) => e.stopPropagation()}>
                    <EditDeductionDialog deduction={d} employeeName={employee?.name ?? "-"} />
                    <Button
                      size="icon"
                      variant="ghost"
                      className="text-destructive"
                      disabled={pending}
                      onClick={() =>
                        startTransition(async () => {
                          const res = await deleteDeduction(d.id);
                          if (res?.error) toast.error(res.error);
                          else toast.success(res?.message ?? t.deductions.deletedDeduction);
                        })
                      }
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </TableCell>
                )}
              </TableRow>
            );
          })}
        </TableBody>
      </Table>
    </div>
      )}

      <DeductionDetailsDialog deduction={details} ctx={details ? context[details.id] ?? {} : {}} onClose={() => setDetails(null)} />
    </div>
  );
}
