"use client";

import { deductionTypeLabel } from "@/lib/i18n/labels";
import { useFormStatus } from "react-dom";
import { useActionState, useState } from "react";
import { Pencil } from "lucide-react";
import { updateDeduction } from "@/lib/actions/deductions";
import { useActionFeedback, keepFilledFields } from "@/hooks/use-action-feedback";
import { useT } from "@/components/providers/locale-provider";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Deduction, DeductionType } from "@/lib/types";

const DEDUCTION_TYPES: DeductionType[] = ["late", "absence", "early_leave", "permission", "unauthorized_exit", "penalty", "advance", "admin_deduction", "other"];

function SaveButton() {
  const { pending } = useFormStatus();
  const t = useT();
  return <Button type="submit" disabled={pending}>{pending ? t.common.saving : t.common.save}</Button>;
}

/** Change any detail of a deduction — including one the system posted, which then stays as set here. */
export function EditDeductionDialog({ deduction, employeeName }: { deduction: Deduction; employeeName: string }) {
  const t = useT();
  const [open, setOpen] = useState(false);
  const [state, formAction] = useActionState(updateDeduction, {});
  useActionFeedback(state, () => setOpen(false));

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button size="icon" variant="ghost" aria-label={t.deductions.editDeduction} title={t.deductions.editDeduction}>
          <Pencil className="h-4 w-4" />
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t.deductions.editDeduction} — {employeeName}</DialogTitle>
          {deduction.autoGenerated && <DialogDescription>{t.deductions.editSystemHint}</DialogDescription>}
        </DialogHeader>
        <form action={formAction} ref={keepFilledFields} className="flex flex-col gap-4">
          <input type="hidden" name="id" value={deduction.id} />
          <div className="flex flex-col gap-1.5">
            <Label>{t.deductions.formType}</Label>
            <Select name="type" defaultValue={deduction.type}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {DEDUCTION_TYPES.map((value) => (
                  <SelectItem key={value} value={value}>{deductionTypeLabel(value, t)}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="flex flex-col gap-1.5">
              <Label htmlFor={`amount-${deduction.id}`}>{t.deductions.formAmount}</Label>
              <Input id={`amount-${deduction.id}`} name="amount" type="number" min={1} defaultValue={deduction.amount} required />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor={`date-${deduction.id}`}>{t.deductions.formDate}</Label>
              <Input id={`date-${deduction.id}`} name="date" type="date" defaultValue={deduction.date} required />
            </div>
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor={`reason-${deduction.id}`}>{t.deductions.formReason}</Label>
            <Input id={`reason-${deduction.id}`} name="reason" defaultValue={deduction.reason} required minLength={3} />
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor={`notes-${deduction.id}`}>{t.common.optionalNotes}</Label>
            <Textarea id={`notes-${deduction.id}`} name="notes" defaultValue={deduction.notes ?? ""} />
          </div>
          <DialogFooter><SaveButton /></DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
