-- Pay types, work schedules and configurable pay rules. Additive only: nothing is dropped or rewritten,
-- and every existing employee is linked to the pay type and schedule matching what they already had.

-- CreateTable
CREATE TABLE `PayType` (
    `id` VARCHAR(191) NOT NULL,
    `code` VARCHAR(191) NULL,
    `name` VARCHAR(191) NOT NULL,
    `basis` ENUM('monthly', 'daily') NOT NULL DEFAULT 'monthly',
    `dayDivisor` DOUBLE NOT NULL DEFAULT 30,
    `hoursPerDay` DOUBLE NULL,
    `workStart` VARCHAR(191) NULL,
    `workEnd` VARCHAR(191) NULL,
    `overtimeStart` VARCHAR(191) NULL,
    `graceMinutes` DOUBLE NOT NULL DEFAULT 0,
    `lateMultiplier` DOUBLE NOT NULL DEFAULT 1.5,
    `overtimeMultiplier` DOUBLE NOT NULL DEFAULT 1.5,
    `overtimeMinimumMinutes` INTEGER NOT NULL DEFAULT 60,
    `overtimeStepMinutes` INTEGER NOT NULL DEFAULT 30,
    `overtimeAutoApprove` BOOLEAN NOT NULL DEFAULT true,
    `permissionMultiplier` DOUBLE NOT NULL DEFAULT 1,
    `unauthorizedExitMultiplier` DOUBLE NOT NULL DEFAULT 1.5,
    `fridayMultiplier` DOUBLE NOT NULL DEFAULT 2,
    `holidayMultiplier` DOUBLE NOT NULL DEFAULT 2,
    `thursdayRuleEnabled` BOOLEAN NOT NULL DEFAULT false,
    `thursdayWorkEnd` VARCHAR(191) NULL,
    `thursdayExtraMultiplier` DOUBLE NOT NULL DEFAULT 1,
    `permittedAbsenceDays` DOUBLE NOT NULL DEFAULT 1,
    `unpermittedAbsenceDays` DOUBLE NOT NULL DEFAULT 2,
    `leaveNoticeHours` INTEGER NOT NULL DEFAULT 48,
    `active` BOOLEAN NOT NULL DEFAULT true,
    `sortOrder` INTEGER NOT NULL DEFAULT 0,
    `deletedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `PayType_code_key`(`code`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `WorkSchedule` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `startTime` VARCHAR(191) NOT NULL,
    `endTime` VARCHAR(191) NOT NULL,
    `overtimeStart` VARCHAR(191) NULL,
    `active` BOOLEAN NOT NULL DEFAULT true,
    `sortOrder` INTEGER NOT NULL DEFAULT 0,
    `deletedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AlterTable: Employee
ALTER TABLE `Employee`
    ADD COLUMN `payTypeId` VARCHAR(191) NULL,
    ADD COLUMN `workScheduleId` VARCHAR(191) NULL,
    ADD COLUMN `customWorkStart` VARCHAR(191) NULL,
    ADD COLUMN `customWorkEnd` VARCHAR(191) NULL,
    ADD COLUMN `customOvertimeStart` VARCHAR(191) NULL;
CREATE INDEX `Employee_payTypeId_idx` ON `Employee`(`payTypeId`);
CREATE INDEX `Employee_workScheduleId_idx` ON `Employee`(`workScheduleId`);
ALTER TABLE `Employee` ADD CONSTRAINT `Employee_payTypeId_fkey` FOREIGN KEY (`payTypeId`) REFERENCES `PayType`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `Employee` ADD CONSTRAINT `Employee_workScheduleId_fkey` FOREIGN KEY (`workScheduleId`) REFERENCES `WorkSchedule`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AlterTable: Overtime — system-posted additions, with their original values kept
ALTER TABLE `Overtime`
    ADD COLUMN `kind` VARCHAR(191) NOT NULL DEFAULT 'overtime',
    ADD COLUMN `multiplier` DOUBLE NULL,
    ADD COLUMN `autoGenerated` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `systemKey` VARCHAR(191) NULL,
    ADD COLUMN `originalHours` DOUBLE NULL,
    ADD COLUMN `originalAmount` INTEGER NULL,
    ADD COLUMN `editedBy` VARCHAR(191) NULL,
    ADD COLUMN `editedAt` DATETIME(3) NULL,
    ADD COLUMN `voidedBy` VARCHAR(191) NULL,
    ADD COLUMN `voidedAt` DATETIME(3) NULL;
CREATE UNIQUE INDEX `Overtime_systemKey_key` ON `Overtime`(`systemKey`);

-- AlterTable: Deduction — two new kinds (widening the enum keeps every existing value) and the original amount
ALTER TABLE `Deduction` MODIFY `type` ENUM('late', 'absence', 'early_leave', 'permission', 'unauthorized_exit', 'penalty', 'advance', 'admin_deduction', 'other') NOT NULL;
ALTER TABLE `Deduction` ADD COLUMN `originalAmount` INTEGER NULL;
UPDATE `Deduction` SET `originalAmount` = `amount` WHERE `autoGenerated` = true AND `editedAt` IS NULL;

-- AlterTable: settings
ALTER TABLE `AttendanceSettings` ADD COLUMN `weeklyOffDays` VARCHAR(191) NOT NULL DEFAULT '5';
ALTER TABLE `PayrollSettings` ADD COLUMN `payPeriodStartDay` INTEGER NOT NULL DEFAULT 26;

-- Seed: the two built-in pay types. Their values are only starting points; everything is edited from /settings.
INSERT INTO `PayType` (`id`, `code`, `name`, `basis`, `dayDivisor`, `workStart`, `workEnd`, `overtimeStart`,
    `graceMinutes`, `lateMultiplier`, `overtimeMultiplier`, `overtimeMinimumMinutes`, `overtimeStepMinutes`,
    `permissionMultiplier`, `unauthorizedExitMultiplier`, `fridayMultiplier`, `holidayMultiplier`,
    `thursdayRuleEnabled`, `thursdayWorkEnd`, `thursdayExtraMultiplier`, `sortOrder`, `updatedAt`)
VALUES
    ('paytype-monthly', 'monthly', 'موظف شهري', 'monthly', 30, '08:00', '18:00', '18:00',
     0, 1.5, 1.5, 60, 30, 1, 1.5, 2, 2, false, NULL, 1, 1, CURRENT_TIMESTAMP(3)),
    ('paytype-daily', 'daily', 'يومية', 'daily', 26, '08:00', '18:30', '18:30',
     0, 1.5, 1.5, 60, 30, 1, 1.5, 2, 2, true, '16:30', 1, 2, CURRENT_TIMESTAMP(3));

-- Seed: the three default fixed schedules.
INSERT INTO `WorkSchedule` (`id`, `name`, `startTime`, `endTime`, `overtimeStart`, `sortOrder`, `updatedAt`)
VALUES
    ('schedule-0800-1630', '08:00 → 16:30', '08:00', '16:30', NULL, 1, CURRENT_TIMESTAMP(3)),
    ('schedule-0800-1800', '08:00 → 18:00', '08:00', '18:00', NULL, 2, CURRENT_TIMESTAMP(3)),
    ('schedule-0800-1830', '08:00 → 18:30', '08:00', '18:30', NULL, 3, CURRENT_TIMESTAMP(3));

-- Existing employees keep exactly what they had: the pay type matching their pay basis, and the schedule
-- matching their shift's times — or, when no schedule matches (evening / night shifts), their shift's own
-- times as custom times.
UPDATE `Employee` SET `payTypeId` = CONCAT('paytype-', `salaryType`) WHERE `payTypeId` IS NULL;
UPDATE `Employee` e JOIN `Shift` s ON s.`id` = e.`shiftId`
    JOIN `WorkSchedule` w ON w.`startTime` = s.`startTime` AND w.`endTime` = s.`endTime` AND w.`deletedAt` IS NULL
    SET e.`workScheduleId` = w.`id`
    WHERE e.`workScheduleId` IS NULL AND e.`customWorkStart` IS NULL;
UPDATE `Employee` e JOIN `Shift` s ON s.`id` = e.`shiftId`
    SET e.`customWorkStart` = s.`startTime`, e.`customWorkEnd` = s.`endTime`
    WHERE e.`workScheduleId` IS NULL AND e.`customWorkStart` IS NULL;
