"use client";

import { useActionState, useState, useTransition } from "react";
import { useFormStatus } from "react-dom";
import { Pencil, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { deleteOvertime, updateOvertime } from "@/lib/actions/overtime";
import { keepFilledFields, useActionFeedback } from "@/hooks/use-action-feedback";
import { useT } from "@/components/providers/locale-provider";
import { Overtime } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import {
  AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription,
  AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger,
} from "@/components/ui/alert-dialog";

function SaveButton() {
  const { pending } = useFormStatus();
  const t = useT();
  return <Button type="submit" disabled={pending}>{pending ? t.common.saving : t.common.save}</Button>;
}

/** Edit an addition's hours or rate. A system-calculated one keeps its calculated value on record. */
export function EditOvertimeDialog({ overtime, employeeName }: { overtime: Overtime; employeeName: string }) {
  const t = useT();
  const [open, setOpen] = useState(false);
  const [state, formAction] = useActionState(updateOvertime, {});
  useActionFeedback(state, () => setOpen(false));
  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button size="icon" variant="ghost" aria-label={t.overtime.editTitle} title={t.overtime.editTitle}>
          <Pencil className="h-4 w-4" />
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t.overtime.editTitle} — {employeeName}</DialogTitle>
          {overtime.autoGenerated && <DialogDescription>{t.overtime.editSystemHint}</DialogDescription>}
        </DialogHeader>
        <form action={formAction} ref={keepFilledFields} className="flex flex-col gap-4">
          <input type="hidden" name="id" value={overtime.id} />
          <div className="grid grid-cols-2 gap-4">
            <div className="flex flex-col gap-1.5">
              <Label htmlFor={`ot-hours-${overtime.id}`}>{t.overtime.formHours}</Label>
              <Input id={`ot-hours-${overtime.id}`} name="hours" type="number" min={0} step="0.25" defaultValue={overtime.hours} required />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor={`ot-rate-${overtime.id}`}>{t.overtime.formRate}</Label>
              <Input id={`ot-rate-${overtime.id}`} name="hourlyRate" type="number" min={0} defaultValue={overtime.hourlyRate} required />
            </div>
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor={`ot-notes-${overtime.id}`}>{t.overtime.formNotes}</Label>
            <Textarea id={`ot-notes-${overtime.id}`} name="notes" defaultValue={overtime.notes ?? ""} />
          </div>
          <DialogFooter><SaveButton /></DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

/** Remove an addition; a system-calculated one is only set aside, so its calculation stays on record. */
export function DeleteOvertimeButton({ overtime }: { overtime: Overtime }) {
  const t = useT();
  const [pending, startTransition] = useTransition();
  return (
    <AlertDialog>
      <AlertDialogTrigger asChild>
        <Button size="icon" variant="ghost" className="text-destructive hover:text-destructive" aria-label={t.overtime.deleteTitle} disabled={pending}>
          <Trash2 className="h-4 w-4" />
        </Button>
      </AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>{t.overtime.deleteTitle}</AlertDialogTitle>
          <AlertDialogDescription>{overtime.autoGenerated ? t.overtime.deleteSystemConfirm : t.overtime.deleteConfirm}</AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel>{t.common.cancel}</AlertDialogCancel>
          <AlertDialogAction
            onClick={() =>
              startTransition(async () => {
                const res = await deleteOvertime(overtime.id);
                if (res.error) toast.error(res.error);
                else toast.success(res.message ?? t.overtime.deleted);
              })
            }
          >
            {t.common.delete}
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
