"use client";

import { useMemo, useState, useTransition } from "react";
import { toast } from "sonner";
import { Check, X, TimerReset } from "lucide-react";
import { Overtime, Employee, RequestStatus } from "@/lib/types";
import { decideOvertime } from "@/lib/actions/overtime";
import { formatEGP } from "@/lib/constants";
import { overtimeKindLabel, requestStatusLabel } from "@/lib/i18n/labels";
import { format } from "@/lib/i18n/format";
import { Badge } from "@/components/ui/badge";
import { DeleteOvertimeButton, EditOvertimeDialog } from "@/components/overtime/edit-overtime-dialog";
import { useLocale, useT } from "@/components/providers/locale-provider";
import { RequestStatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import { MultiSelectFilter } from "@/components/shared/multi-select-filter";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import { EmptyState } from "@/components/shared/empty-state";

const STATUS_OPTIONS: RequestStatus[] = ["pending", "approved", "rejected"];

export function OvertimeTable({
  records,
  employees,
  canApprove,
  canManage = false,
  initialStatus = "all",
}: {
  records: Overtime[];
  employees: Employee[];
  canApprove: boolean;
  /** may edit or remove entries (the overtime permission) */
  canManage?: boolean;
  /** Status filter to pre-select, e.g. from a dashboard KPI link (`?status=approved`). */
  initialStatus?: string;
}) {
  const t = useT();
  const locale = useLocale();
  const empMap = new Map(employees.map((e) => [e.id, e]));
  const [pending, startTransition] = useTransition();
  const [status, setStatus] = useState<string[]>(initialStatus === "all" ? [] : [initialStatus]);

  const rows = useMemo(
    () => records.filter((o) => status.length === 0 || status.includes(o.status)),
    [records, status],
  );

  function decide(id: string, decision: "approved" | "rejected") {
    startTransition(async () => {
      const res = await decideOvertime(id, decision);
      if (res?.error) toast.error(res.error);
      else toast.success(decision === "approved" ? t.overtime.approved : t.overtime.rejected);
    });
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex justify-end">
        <MultiSelectFilter
          className="sm:w-48"
          placeholder={t.common.allStatuses}
          selected={status}
          onChange={setStatus}
          options={STATUS_OPTIONS.map((value) => ({ value, label: requestStatusLabel(value, t) }))}
        />
      </div>

      {rows.length === 0 ? (
        <EmptyState icon={TimerReset} title={t.overtime.noRecords} />
      ) : (
      <div className="overflow-hidden rounded-xl border border-border">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>{t.overtime.colEmployee}</TableHead>
            <TableHead>{t.overtime.colDate}</TableHead>
            <TableHead>{t.overtime.colKind}</TableHead>
            <TableHead>{t.overtime.colHours}</TableHead>
            <TableHead>{t.overtime.colRate}</TableHead>
            <TableHead>{t.overtime.colAmount}</TableHead>
            <TableHead>{t.overtime.colStatus}</TableHead>
            {(canApprove || canManage) && <TableHead className="text-end">{t.overtime.colActions}</TableHead>}
          </TableRow>
        </TableHeader>
        <TableBody>
          {rows.map((o) => {
            const employee = empMap.get(o.employeeId);
            return (
              <TableRow key={o.id}>
                <TableCell>
                  <div className="font-medium">{employee?.name ?? "-"}</div>
                  {employee && <div dir="ltr" className="text-xs text-muted-foreground">{employee.employeeNumber}</div>}
                </TableCell>
                <TableCell>{o.date}</TableCell>
                <TableCell>
                  <div className="flex flex-col gap-1">
                    <span>{overtimeKindLabel(o.kind, t)}{o.multiplier ? ` × ${o.multiplier}` : ""}</span>
                    {o.autoGenerated && (
                      <Badge variant="outline" className="w-fit" title={o.editedBy ? o.editedBy : undefined}>
                        {o.editedBy ? t.overtime.systemEdited : t.overtime.fromSystem}
                      </Badge>
                    )}
                  </div>
                </TableCell>
                <TableCell className="tabular-nums">{o.hours}</TableCell>
                <TableCell className="tabular-nums">{formatEGP(o.hourlyRate, locale)}</TableCell>
                <TableCell className="tabular-nums font-medium">
                  {formatEGP(o.amount, locale)}
                  {o.editedBy && o.originalAmount != null && (
                    <div className="text-xs font-normal text-muted-foreground">
                      {format(t.overtime.original, { hours: o.originalHours ?? "—", amount: formatEGP(o.originalAmount, locale) })}
                    </div>
                  )}
                </TableCell>
                <TableCell><RequestStatusBadge status={o.status} /></TableCell>
                {(canApprove || canManage) && (
                  <TableCell className="text-end">
                    <div className="flex justify-end gap-1">
                      {canApprove && o.status === "pending" && (
                        <>
                          <Button size="icon" variant="ghost" className="text-success" disabled={pending} onClick={() => decide(o.id, "approved")}>
                            <Check className="h-4 w-4" />
                          </Button>
                          <Button size="icon" variant="ghost" className="text-destructive" disabled={pending} onClick={() => decide(o.id, "rejected")}>
                            <X className="h-4 w-4" />
                          </Button>
                        </>
                      )}
                      {canManage && (
                        <>
                          <EditOvertimeDialog overtime={o} employeeName={employee?.name ?? "-"} />
                          <DeleteOvertimeButton overtime={o} />
                        </>
                      )}
                    </div>
                  </TableCell>
                )}
              </TableRow>
            );
          })}
        </TableBody>
      </Table>
      </div>
      )}
    </div>
  );
}
